<?php

//echo "Hello";

$a = 0;
$b = "Clinton";
$c = array();
$d = ["Ekene", "Vincent", "Gideon", "Ubesie", "Darlington","Peter", "Camillus", "Onyeka", "Bernard"];

echo $a; 
echo "<br>";
echo $b;
echo "<br>";

echo $a."<br>".$b;
$br = "<br>";

echo $br;
echo($a);

echo $br;
echo $br;
echo $br;

$answer = $a + 30;
echo $answer;

echo $br;
echo $br;
echo $br;

if($a >=5) echo "It is equal";
else echo "not equal";

$first_name = "Clinton";
$last_name = "Onuigbo";

//functions
//die();
echo $br;
echo $br;
echo $br;

echo strtolower($first_name);
echo $br;
echo strtoupper($last_name);
echo $br;
$middle_name = "nnamdi";
echo ucfirst($middle_name);
echo $br;
echo strlen("{$first_name} {$last_name}");
echo $br;
echo substr("{$first_name}", 2, 3);
echo $br;
echo substr("{$first_name} {$last_name}", -6, 4);
echo $br;
var_dump($d);
echo $br;
echo "<pre>";
print_r ($d);
echo $br; echo $br;
echo str_replace("o", "a", strtolower("{$first_name} {$last_name}"));
echo $br;
echo "<pre>";
print_r (explode(" ", strtolower("{$first_name} {$last_name} Ugochukwu")));
echo $br;
echo md5('ebere');
echo $br;
echo password_hash('ebere', PASSWORD_DEFAULT);



echo $br;
echo $br;
echo $br;

//CUSTOM FUNCTIONS

// function calculate(){
//     echo 5*30;
// }

// calculate();

function calculate(){
    $response = 5*30;
    return $response;
}

echo calculate();

echo $br;
echo $br;

//create a function that returns exactly 10 string length from a given string input
//The first and last alphabet from the input starts the response while the remaining 8 are autogenerated

function generate($first_value, $second_value, $password = 0) {
    return substr("{$first_value}", 0, 1). substr("{$second_value}",-1, 1). substr(md5($password), 0, 8);
}
 echo generate("Obinna", "Nnamani");

 //Arrays

 $my_students = ["tall"=>"Ekene","fine"=>"Vincent","short"=>"Gideon","stubborn"=>"Ubesie","dark"=>"Darlington","fair"=>"Peter","cool"=>"Camillus","sleepy"=>"Onyeka","late"=>"Benard","clinton"=>["profession"=>"programmer","trader"]];

 $my_array = array(0=>"ford", 1=>"benz", 2=>"peugeut", 3=>"toyota", 4=>"honda", 5=>"lexus", 6=>"kia");

 echo $br;
echo "<pre>";
print_r ($my_array[2]);
echo $br;
print_r ($my_array[4]);
echo $br;
print_r ($my_array[0]);
echo $br;
print_r ($my_students["short"]);
echo $br;
print_r ($my_students["clinton"]["profession"]);

$userID = ["identity"=>
            ["name"=>"Emeka Nwodo", 
            "age"=>"twenty-five"
            ], 
            "interests"=>["football", "basketball"
                        ], 
            "education"=>["tertiary"=>"ESUT", 
                        "secondary"=>"Unssec"
            ], 
            "skills"=>["singing", "dancing"
        ],      

            ];

echo $br;
print_r ($userID["identity"]["name"]);
echo $br;
echo $br;
echo $br;
print_r (($userID["identity"]["name"])." is a ".($userID["identity"]["age"])." years old brilliant young man");

echo $br;
$cars = array(
    array("volvo", 22, 18),
    array("BMW", 15, 13),
    array("Saab", 5, 2),
    array("Land Rover", 17, 15)
);


// echo "<pre>";
// print_r($cars);

echo $br;
echo count($my_students);
echo $br;
print_r($my_students);
echo $br;
print_r (array_keys($my_students));
//For Loops
// for ($i = 0, $i <=)
echo $br;
echo $br;
print_r ($cars);
echo $br;
echo $br;
echo $br;
echo $br;
echo count($cars);
echo $br;
echo $br;
echo count($cars[1]);
echo $br;
echo $br;

echo "<table width='50%' \style='background:pink'>
<thead>
    <tr>

    <th>name</th> <th>stock</th> <th>sold</th>
        </tr>
        </thead>";

for ($i=0; $i < count($cars); $i++) { 
    $data= ($cars[$i]);
    echo"<tr>";

    for ($j=0; $j < count($data) ; $j++) { 
        echo "<td>", $data[$j],
        "</td>";
    }
    echo $br;
}

"</table>"

?>